Docker deployment
nasa/cumulus-template-deploy pull request #66
Opened 2021-08-02 20:13 UTC by laurenfrederick

2021-08-04 23:32 UTC, flamingbear requested changes
This is freaking awesome.  I had a problem with teacache that I couldn't fix, so I'm going to try again tonight. But wanted to get your input on a couple of things and one correction.  But 😍

2021-08-05 17:20 UTC, laurenfrederick commented on docker/README.md
> +- AWS_SECRET_ACCESS_KEY
Yep, good point. Thanks for the suggestion. I have committed it.

2021-08-05 17:25 UTC, laurenfrederick commented on docker/README.md
> +This will print out something l
Yeah not sure how that got deleted. Sorry.

2021-08-05 17:28 UTC, laurenfrederick commented on docker/README.md
> +  - Runs `terraform init`
I added a few things. See what you think.

2021-08-05 17:28 UTC, laurenfrederick commented on docker/README.md
> +- Docker
Fixed.

2021-08-05 17:28 UTC, laurenfrederick commented on docker/README.md
> +
Added some wording to where you start the shell script inside of the container.

2021-08-05 17:28 UTC, laurenfrederick commented on docker/README.md
> +This will print out something l
Fixed.

2021-08-05 17:33 UTC, laurenfrederick commented on docker/prep-deployments.sh
> +  rds_user_password = \"$PREFIX"password"\"
No, they can't be or you get an error. I actually had to push up a fix for when there is a hyphen in the prefix. eek.

2021-08-05 17:36 UTC, laurenfrederick commented on docker/prep-deployments.sh
> +# sed -e 's/var.ecs_cluster_instance_image_id/data.aws_ssm_parameter.ecs_image_id.value/g' main.tf >> main.tf.tmp && mv main.tf.tmp main.tf
yep

2021-08-05 17:36 UTC, laurenfrederick commented on docker/prep-deployments.sh
> +# ../../terraform apply -auto-approve -input=false >> ../../output/data-migration-deployment.txt
👍

2021-08-05 17:36 UTC, laurenfrederick commented on docker/teardown.sh
> +aws s3 rb s3://$PREFIX-public
yes I fixed it a little bit ago

2021-08-05 17:37 UTC, laurenfrederick commented on docker/vpcConfig.tf
> +data "aws_vpc" "application_vpcs" {
It's finding a VPC with the name "Application VPC", which we're relying on being an NGAP standard here and then creating a VPC resource when it finds that. For the subnet it's using a tag name and again we're relying on the NGAP standard for the tag.

2021-08-06 17:04 UTC, flamingbear approved these changes

2021-08-06 17:04 UTC, flamingbear commented
This looks great now.

2021-08-06 17:31 UTC, nemreid requested changes
Blocking on potential concern about resources left behind from teardown.

2021-08-06 20:16 UTC, nemreid commented on docker/README.md
> +## Run in a separate terminal to create the tunnel:
```suggestion
## Configure with path to keypair and run in a separate terminal to create the tunnel:
```

2021-08-06 20:16 UTC, nemreid commented on docker/README.md
> +ssh -p 4343 -N -L 8000:abcdefghij.execute-api.us-east-1.amazonaws.com:443 ec2-user@localhost
```suggestion
ssh -p 4343 -N -L 8000:abcdefghij.execute-api.us-east-1.amazonaws.com:443 ec2-user@localhost -i path/to/keypair
```

2021-08-06 20:16 UTC, nemreid commented on docker/print-connection-commands.sh
> +## Run in a separate terminal to create the tunnel:
```suggestion
## Configure with path to keypair and run in a separate terminal to create the tunnel:
```

2021-08-06 20:16 UTC, nemreid commented on docker/print-connection-commands.sh
> +ssh -p 4343 -N -L 8000:$api_gateway:443 ec2-user@localhost
```suggestion
ssh -p 4343 -N -L 8000:$api_gateway:443 ec2-user@localhost -i path/to/keypair
```

2021-08-06 23:09 UTC, nemreid approved these changes
👍

2021-08-09 17:53 UTC, merged