Updates Cumulus sources for release 18.2.2
nasa/cumulus-template-deploy pull request #87
Opened 2024-06-04 23:20 UTC by paulpilone

As a result of releasing [Cumulus Core 18.2.2](https://github.com/nasa/cumulus/releases/tag/v18.2.2) (https://bugs.earthdata.nasa.gov/browse/CUMULUS-3736) I've updated the Cumulus sources to point to the new release.

2024-06-04 23:22 UTC, paulpilone commented
There are a few other Cumulus release sources that don't appear to have been updated in awhile so I didn't update them:

- https://github.com/nasa/cumulus-template-deploy/blob/0cf1043dc53f8cf01599700c1c13e0243157279c/cumulus-tf/additions.tf.example#L105
- https://github.com/nasa/cumulus-template-deploy/blob/0cf1043dc53f8cf01599700c1c13e0243157279c/cumulus-tf/hello_world_workflow.tf#L2

Happy to update those as well if it makes sense.

2024-06-04 23:23 UTC, paulpilone commented
Also, once this gets merged should we tag and issue a new release?

2024-06-05 14:33 UTC, npauzenga requested changes
Thanks @paulpilone! I think we should go ahead and update those couple sources from v15/17 to 18.2.2. They must have just been missed as I can't see why we'd want users to take workflows from previous versions. I'll bet those workflows haven't been updated since those versions but still.

2024-06-05 14:35 UTC, npauzenga commented
> Also, once this gets merged should we tag and issue a new release?

Yeah, I'm guessing we haven't been doing this as much because the release artifact here is just a .zip archive so it's not as critical. Cloning and updating is likely the common route with this repo. Probably should issue a new 'release' to avoid any confusion.

2024-06-05 15:22 UTC, npauzenga approved these changes
👍

2024-06-05 15:33 UTC, merged